import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { IRadioPageProps } from "utils/types";
import Radio from "components/Radio";

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jobapi.teclead-ventures.de/recruiting/radios");
  const radios = (await res.json()) as IRadioPageProps;

  return {
    props: radios,
  };
};

const Home: NextPage<IRadioPageProps> = ({ radios }) => {
  return (
    <>
      <Head>
        <title>Radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Radio radios={radios} />
    </>
  );
};

export default Home;
